---
 - name: "Installing EPEL-RELEASE in Redhat"
   yum: 
     name: epel-release
     state: present
 - name: "Installing nginx in Redhat"
   yum:
     name: nginx
     state: present

- name: copying index.html
  copy:
    src: index.centos.html
    dest: /var/www/html/
  notify:
    - restart nginx
 - name: "starting nginx"
   service:
     name: nginx
     state: started
